# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    releaes:
      type: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        make
        mv saka saka-x86_64-linux
    
    - name: Build
      run: |
        make OS=Windows_NT
        mv saka.exe saka-x86_64-windows.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          saka-x86_64-linux
          saka-x86_64-windows.exe
