# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install mingw
      run: |
        sudo apt install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.23'

    - name: Build
      run: |
        make VERSION=${GITHUB_REF#refs/*/}
        mv saka saka-x86_64-linux
    
    - name: Build
      run: |
        make VERSION=${GITHUB_REF#refs/*/} OS=Windows_NT
        mv saka.exe saka-x86_64-windows.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          saka-x86_64-linux
          saka-x86_64-windows.exe
